---
title: "lobster_abundance_stats"
author: "Gabriel De La Rosa, Dylan Glave"
date: "11/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include = FALSE,echo = TRUE, warning = FALSE)
```



```{r}
### Reading in Packages

library(tidyverse)
library(janitor)
library(effsize)
library(here)
library(kableExtra)
```



```{r}
### Reading in Packages

lobster_abundance <- read_csv("lobster_abundance_sbc_lter.csv", na = "-99999") %>% 
  clean_names() 
```



```{r}
### Expanding longer with "uncount()" function. Row with "45" lobsters, will now be 45 observations. Removed "count" row and gives each counted lobster its own rown

lobster_tidy <- lobster_abundance %>% 
  tidyr::uncount(count)
```


```{r}
#### Each lobster now has its own row. 1 variable per column, 1 observation per row AND 1 measurement per cell. 

#### Adding a new column to show the year and month name of each lobster observation: 


#### Parsed date_new column to get month and year separated. 

lobster_parse_date <- lobster_tidy %>% 
  mutate(obs_month = lubridate::month(date, label = TRUE),
         obs_year = lubridate::year(date))
view(lobster_parse_date)
```

```{r}
# Yearly counts by site

lob_year <- lobster_abundance %>% 
  group_by(year, site) %>%
  count(year)

#  Graph these data...

site_graph <- ggplot(data = lob_year, aes(x = year, y = n)) +
  geom_col() +
  facet_wrap("site")

site_graph
```


```{r}
# Results B:

# Pare down data to year, size, site for 2012 and 2018

size_dist <- lobster_parse_date %>% 
  filter(year == c("2018", "2012")) %>%
  select(year, size_mm, site) 

# Divide data frame by year
  
size_2012 <- size_dist %>% 
  filter(year == "2012")

# Compare size distributions across sites...

ggplot(data = size_dist, aes(x = size_mm)) +
  geom_histogram() +
  facet_wrap(c("site"))




